// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000/api/v1' | (string & {});
};

export type AuthRequest = {
    email: string;
    password: string;
};

export type User = {
    id: number;
    email: string;
};

export type AuthResponse = {
    /**
     * Only returned for mobile clients.
     */
    token?: string;
    user: User;
};

export type CurrentUserResponse = {
    user: User | null;
};

export type MessageResponse = {
    message: string;
};

export type ErrorResponse = {
    error: string;
};

export type SignupData = {
    body: AuthRequest;
    path?: never;
    query?: never;
    url: '/signup';
};

export type SignupErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    422: ErrorResponse;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * Authenticated user
     */
    201: AuthResponse;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type LoginData = {
    body: AuthRequest;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    422: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Authenticated user
     */
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type LogoutResponses = {
    /**
     * Logout confirmation
     */
    200: MessageResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetCurrentUserErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * Current user or null
     */
    200: CurrentUserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];
